dist:     trusty    # используем Ubuntu 14.04 Trusty Tahr (а не 12.02 Precise Pangolin)
sudo:     required  # используем Virtual Machine (а не Docker container)

language: cpp       # на практике разницы между специфичным для C++ окружением
                    # и, скажем, python -- никакой. Но пусть будет cpp.

os: osx
    # будем прогонять CI и на Linux, и на Mac OS X...

compiler: clang
    # ... и с помощью GCC, и Clang

before_cache:
  - brew cleanup

cache:
    directories:
        - $HOME/Library/Caches/Homebrew

before_install:
    - curl -sSL https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer | bash -s stable
    - brew install sfml

script:
    # скрипт сборки и тестирования проекта:
    - cd CI
    - cmake CMakeListsCI.txt ..
    - make
